### ISSUE TITLE
Hello from picotui

### ISSUE THREAD

**Issue by pfalcon** [atalax/wytch#1]
FYI, I got dissatisfied with existing Python TUI frameworks too, resulting in https://github.com/pfalcon/picotui , replacing npyscreen for https://github.com/pfalcon/ScratchABit . No geometry managers and stuff, on the other hand, MicroPython-friendly.

**Comment by atx** [comment]
Acknowledged. I first saw picotui when I started writing wytch (after finishing [fytui](https://github.com/atalax/python-feeltech/blob/master/bin/fytui)), but was worried that the MicroPython compatability might eventually get in the way.

**Comment by pfalcon** [comment]
I see, glad to know you had it in mind. From my point of view, of course MicroPython compatibility is nice feature which defines project scope, not a limitation. I also added a (ranty) description why picotui was born to the project README.
